# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64af350bc68aa40d5a441033e8904e4fc8f140262a3f7dcb3d5697d1835feb37b2c03d0faa79e8d33ca337cdc4ba20fe9e3e9c753eeb0c8ac46a7a6c8255321a

test:
  secret_key_base: c8733ef7de36e8a6c32e2e276ecffcfac4dd058db4930f77e90647f4590766965fe6fee8cce955ed1cd2e04cc6fc8fe63f6da6f22c7789419d70ff1936626a7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
